-- MySQL Script generated by MySQL Workbench
-- Tue Feb  5 19:28:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frdb` DEFAULT CHARACTER SET utf8 ;
USE `frdb` ;

-- -----------------------------------------------------
-- Table `frdb`.`fr_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frdb`.`fr_log` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `log_user` VARCHAR(45) NULL,
  `log_pass` VARCHAR(45) NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frdb`.`fr_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frdb`.`fr_request` (
  `id_request` INT NOT NULL AUTO_INCREMENT,
  `fr_code_hex` VARCHAR(45) NULL,
  `re_nome` VARCHAR(45) NULL,
  `re_cpf` VARCHAR(45) NULL,
  `re_filiap` VARCHAR(45) NULL,
  `re_filiam` VARCHAR(45) NULL,
  `re_datnas` DATE NULL,
  `re_tel` VARCHAR(45) NULL,
  `re_tel2` VARCHAR(45) NULL,
  `re_endereco` VARCHAR(65) NULL,
  `re_n_casa` INT NULL,
  `re_email` VARCHAR(45) NULL,
  `re_tipo_causa` VARCHAR(45) NULL,
  `re_tipo_modo` VARCHAR(45) NULL,
  `re_num_proc` VARCHAR(45) NULL,
  `re_date_req` DATE NULL,
  `re_datepedido` VARCHAR(45) NULL,
  PRIMARY KEY (`id_request`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frdb`.`fr_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frdb`.`fr_data` (
  `id_data` INT NOT NULL AUTO_INCREMENT,
  `dat_code` VARCHAR(65) NULL,
  `dat_tipo` VARCHAR(45) NULL,
  `fr_request_id_request` INT NOT NULL,
  `dat_size` VARCHAR(45) NULL,
  `dat_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_data`),
  INDEX `fk_fr_data_fr_request1_idx` (`fr_request_id_request` ASC),
  CONSTRAINT `fk_fr_data_fr_request1`
    FOREIGN KEY (`fr_request_id_request`)
    REFERENCES `frdb`.`fr_request` (`id_request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `frdb`.`fr_log` (`log_user`, `log_pass`) VALUES ('informix', '5895]311');

